(cl:in-package scara_inverse_kinematics-srv)
(cl:export '(R11-VAL
          R11
          R12-VAL
          R12
          R13-VAL
          R13
          R21-VAL
          R21
          R22-VAL
          R22
          R23-VAL
          R23
          R31-VAL
          R31
          R32-VAL
          R32
          R33-VAL
          R33
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          THETA1-VAL
          THETA1
          THETA2-VAL
          THETA2
          D3-VAL
          D3
))